### ISSUE TITLE
如何修改rem的比例

### ISSUE THREAD

**Issue by zhaoaaaaa5** [cipchk/vscode-cssrem#10]
可以自己定义px转rem的比例吗？我看到只有一个16px = 1rem的默认设置。

**Comment by cipchk** [comment]
我不明白所指的比例是什么意思？若是指 `rootFontSize` 则可以在项目配置里添加：

```json
"cssrem.rootFontSize": 20
```

来改变基准，则当输入： `16px` 时结果是： `16/20=0.8rem`

**Comment by zhaoaaaaa5** [comment]
是的， 就是设置 `“ cssrem.rootFontSize ”： 20`，改变基准，但是如何打开您的这个项目配置

**Comment by cipchk** [comment]
![wechat screenshot_20180830134412](https://user-images.githubusercontent.com/2987467/44831816-cbbd1200-ac5a-11e8-992f-eeb0d69bb87f.png)

**Comment by zhaoaaaaa5** [comment]
非常感谢您的耐心解答，您的插件很好用。
