### ISSUE TITLE
只有height的时候才会弹出，width,font-size,margin，padding后面都不行

### ISSUE THREAD

**Issue by xafzz** [cipchk/vscode-cssrem#11]
比如 height:20p 会弹出 对应的rem
width,font-size等都不会弹出对应的rem,只有px

**Comment by xafzz** [comment]
- [ ] 
![1111111](https://user-images.githubusercontent.com/25863091/49057034-f2c6b800-f238-11e8-986c-a7ad8953e20c.png)
![22222222](https://user-images.githubusercontent.com/25863091/49057036-f2c6b800-f238-11e8-8a46-9cde670cbcaa.png)
![333333](https://user-images.githubusercontent.com/25863091/49057037-f35f4e80-f238-11e8-912c-922552b4e523.png)
![4444444](https://user-images.githubusercontent.com/25863091/49057040-f3f7e500-f238-11e8-89f7-c942702af847.png)

**Comment by cipchk** [comment]
我想应该是编码格式引起的，一般而言，一个合理的编码风格应该是：

```css
font-size: 10px;
```

属性与单位中间应该有个空格，有关更多风格指南，请参考：https://google.github.io/styleguide/htmlcssguide.html

**Comment by cipchk** [comment]
我会修复这种不标准风格指南的使用。

**Comment by xafzz** [comment]
> 我想应该是编码格式引起的，一般而言，一个合理的编码风格应该是：
> 
> ```css
> font-size：10px;
> ```
> 
> 属性与单位中间应该有个空格，有关更多风格指南，请参考：[https](https://google.github.io/styleguide/htmlcssguide.html)：//google.github.io/styleguide/htmlcssguide.html[](https://google.github.io/styleguide/htmlcssguide.html)

谢谢，是我没有搞明白。
是我习惯这种写法导致的
