### ISSUE TITLE
希望在转成rem后生成原px的注释

### ISSUE THREAD

**Issue by ZH4L** [cipchk/vscode-cssrem#14]
比如我输入`10px`转成rem后变成`0.123rem`，后面维护代码的时候就不知道之前对应设计图里的px数是多少了，所以希望转成rem后自动加个原先是多少px的注释

**Comment by cipchk** [comment]
一般来说一个项目的 rem 基数都是固定的，你可以在项目根目录下创建针对 VSCODE 的配置，例如 `.vscode/settings.json` 下统一设置 `cssrem.rootFontSize` 即可。

**Comment by rukihu** [comment]
感谢作者的插件，很好用。
希望增加这个功能，主要是给后期维护的人看。
比如
`body {
  font-size: 1rem /*16px*/
}`
或者做个配置开关，是否开启注释！
再或者就是当我鼠标移动到1rem的时候，会提示是多少像素。

**Comment by cipchk** [comment]
鼠标悬停这个可以有，有时间我会加上。

**Comment by LBC000** [comment]
我希望去掉怎么去除?

**Comment by cipchk** [comment]
> 我希望去掉怎么去除?

设置 `cssrem.addMark` 值。
