### ISSUE TITLE
添加忽略值

### ISSUE THREAD

**Issue by hdyusf** [cipchk/vscode-cssrem#15]
有时候会需要显示0.5px线或者1px边 等等
可以考虑增加一个忽略值
字符串格式 '0.5|1|2'
数组 [0.5, 1, 2]
等都可以

**Comment by cipchk** [comment]
@hdyusf 忽略值的意义是什么呢？我不是很理解，插件并不会影响 `0.5px` 的键入，能否进一步描述。

**Comment by hdyusf** [comment]
写一个px单位转换一次比较麻烦 所以局部替换和全文替换使用较多
但是目前插件会将所有的px单位都替换为rem
忽略值的作用在于局部或全文替换时 忽略掉指定的px值 例如边框的1px 0.5的线 2px的阴影等等

**Comment by hdyusf** [comment]
在px转rem时 rem的单位忽略掉了小数点六位之后的值 会造成在页面显示为px值时 有一个上下浮动的范围 
 如果使用了全文替换 就需要手动将某些精度较高的线条单位从rem转换为px单位 不太友好
