### ISSUE TITLE
cssrem.rootFontSize setting only work after reopen vscode

### ISSUE THREAD

**Issue by VitorLuizC** [cipchk/vscode-cssrem#2]
After change `cssrem.rootFontSize` on `settings.json` the helper did't apply it.

![Screencast GIF](http://g.recordit.co/u6aLExUutz.gif)

Helper just apply `cssrem.rootFontSize` setting after reopen VSCode, by the way your extension is pretty awesome!

**Comment by cipchk** [comment]
@VitorLuizC Thank you, do you hava any details? i can't reproduce that on my vscode environment;

![test](https://user-images.githubusercontent.com/2987467/26940137-28feb37a-4cac-11e7-9797-70e91b3da1cb.gif)

**Comment by VitorLuizC** [comment]
My environment and extensions:

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063

|Extension|Author|Version|
|---|---|---|
|theme-monokai-light|anoff|1.0.3|
|monokai-one-dark-vivid|ashpowell|0.6.0|
|vscode-icontheme-nomo-dark|be5invis|1.3.0|
|vscode-standardjs|chenxsan|1.1.4|
|cssrem|cipchk|0.0.3|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.11|
|EditorConfig|EditorConfig|0.9.3|
|vscode-gutter-preview|kisstkondoros|0.9.1|
|typescript-javascript-grammar|ms-vscode|0.0.21|
|vetur|octref|0.7.0|
|vscode-spotify|shyykoserhiy|2.0.0|
|language-stylus|sysoev|1.7.3|
|operatormonodarktheme|Valiantsin|0.4.1|
|vscode-wakatime|WakaTime|1.1.8|
|vscode-todo-highlight|wayou|0.5.5|;

Could be a Windows bug... Or something specific to VSCode on Windows.

**Comment by cipchk** [comment]
@VitorLuizC after change `cssrem.rootFontSize`, are you restart vscode or not?

**Comment by yanjingenious** [comment]
这个问题必须重新安装的，我出现这个问题的原因是：安装后直接关闭vscode， 而不是点击重新加载按钮导致的

**Comment by cipchk** [comment]
you are right. @yanjingenious
