### ISSUE TITLE
px to rpx 在scss文件中无效

### ISSUE THREAD

**Issue by kola-web** [cipchk/vscode-cssrem#25]

**Comment by kola-web** [comment]
![Uploading image.png…]()

**Comment by kola-web** [comment]
![image](https://user-images.githubusercontent.com/46446884/111435587-efbea100-873b-11eb-92f5-297a048bfd23.png)

**Comment by cipchk** [comment]
是否语言模式为 SCSS 呢？因为这里认的是语言模式，而非扩展名。

**Comment by kola-web** [comment]
![image](https://user-images.githubusercontent.com/46446884/111722228-65418300-889c-11eb-8438-1ca25e015b57.png)
语言模式是scss, 我实在vscode中写小程序 通过Live Sass Compiler 插件把scss编译为wxss的

**Comment by kola-web** [comment]
要是能与emmet兼容就更好了

**Comment by cipchk** [comment]
能否提供一个重现的项目呢？若是单独 scss 文件，这里测试并没有问题呢？

**Comment by cipchk** [comment]
关于 emmet 问题，建议重新添加一个新的 issues。

**Comment by kola-web** [comment]
十分感谢你的帮助,这这边应该是由于文件关联导致的问题,已解决
