### ISSUE TITLE
根目录设置 .cssrem 里面的配置为何不生效

### ISSUE THREAD

**Issue by zj1234jz** [cipchk/vscode-cssrem#28]
{
  "rootFontSize": 192,
  "fixedDigits": 3
}

**Comment by wycnewu** [comment]
+1

**Comment by cipchk** [comment]
能否截图 vscode 打开的目录结构图吗？目录查看根目录是以用户打开的当前工作目录。

**Comment by wycnewu** [comment]
> 能否截图 vscode 打开的目录结构图吗？目录查看根目录是以用户打开的当前工作目录。
![image](https://user-images.githubusercontent.com/24403012/117965909-e3c71800-b355-11eb-992d-8c486ae4bf3f.png)

**Comment by cipchk** [comment]
@wycnewu 我在本地上一切正常，gif:

![Kapture 2021-05-12 at 19 48 43](https://user-images.githubusercontent.com/2987467/117970356-25a68d00-b35b-11eb-8648-bd94acf8165b.gif)

**Comment by cipchk** [comment]
@wycnewu 能否打开 vscode 的调试器（帮助-切换开发人员工具），是否有相关异常呢？

**Comment by wycnewu** [comment]
![image](https://user-images.githubusercontent.com/24403012/117970906-d2810a00-b35b-11eb-8595-a7cd082dcdff.png)
优先级低于vscode设置，vscde设置的是36；另外vscode没有报异常

**Comment by cipchk** [comment]
@wycnewu 我尝试给加载配置文件增加几处调试信息，能否麻烦你进一步尝试在开发人员工具下是否有相关的异常数据。以下是安装文件。
[cssrem-2.2.0.vsix.zip](https://github.com/cipchk/vscode-cssrem/files/6470456/cssrem-2.2.0.vsix.zip)

**Comment by zj1234jz** [comment]
你好，有点忙 最近才看到
![Uploading image.png…]()

**Comment by zj1234jz** [comment]
![image](https://user-images.githubusercontent.com/45535845/118352867-60483980-b596-11eb-8529-dac021949957.png)

**Comment by zj1234jz** [comment]
![image](https://user-images.githubusercontent.com/45535845/118352914-9dacc700-b596-11eb-97ee-6180ad2310df.png)

**Comment by zj1234jz** [comment]
![image](https://user-images.githubusercontent.com/45535845/118352934-ba48ff00-b596-11eb-88ba-d6605806e568.png)
