### ISSUE TITLE
是不是来个 rem 也可以转回去 px 的更好？

### ISSUE THREAD

**Issue by smart-z** [cipchk/vscode-cssrem#3]
的确非常易用!
是不是来个 rem 也可以转回去 px 的更好？
刚开始碰rem，一直用 px ，不转回去没安全感。
请指点...

**Comment by cipchk** [comment]
早先是有过这种考虑，但后面一想，`rem` 转 `px` 这种事情本身是无意义的，因为 **cssrem** 本身就是在输入 `[\d]px` 的时候决定 `rem` 的数值，故而这种功能无任何意义。
