### ISSUE TITLE
[BUG反馈] 更新至2.4.0后无法使用

### ISSUE THREAD

**Issue by WhiteCoffee9834** [cipchk/vscode-cssrem#33]
在更新之前使用正常,今天更新后无法使用
![Snipaste_2021-05-30_21-02-20](https://user-images.githubusercontent.com/72718918/120103470-abfc0500-c18a-11eb-8575-39b2f67f6c76.png)
![Snipaste_2021-05-30_21-03-11](https://user-images.githubusercontent.com/72718918/120103471-aef6f580-c18a-11eb-8d92-1ec588756d57.png)

经验证,回退至2.3.0版本后可以正常使用

**Comment by cipchk** [comment]
fixed by `2.4.1`
