### ISSUE TITLE
根目录下的.cssrem无效，控制台报错找不到文件

### ISSUE THREAD

**Issue by dong19950** [cipchk/vscode-cssrem#35]
根目录下的.cssrem无效，控制台报错找不到文件。
version: v2.4.1
error: [Extension Host] Not found file: \D:\demos\size\.cssrem

![image](https://user-images.githubusercontent.com/45591173/122851154-10048a00-d341-11eb-9c3c-c0d9e9d3d5a3.png)

**Comment by cipchk** [comment]
@dong19950 能否安装一下以下版本，看是否解决问题。

[cssrem-2.4.2.vsix.zip](https://github.com/cipchk/vscode-cssrem/files/6691254/cssrem-2.4.2.vsix.zip)

**Comment by dong19950** [comment]
@cipchk 版本v2.4.2可以正常使用了，不过存在一个问题，不知道是否算bug。创建.cssrem文件之后必须重启vscode，否则无法生效，删除也是一样。

**Comment by cipchk** [comment]
> @cipchk 版本v2.4.2可以正常使用了，不过存在一个问题，不知道是否算bug。创建.cssrem文件之后必须重启vscode，否则无法生效，删除也是一样。

是的，需要重启，因为我认为 `.cssrem` 是不常改动的文件，没有必要总是开着专门针对这一文件的监听。如果你想做测试，可以配置 Config 的配置项，它是立即生效的，最终再复制回到 `.cssrem`。

**Comment by cipchk** [comment]
我已经增加 `.cssrem` 对 JSON Comment 的支持，你可以直接在这一文件内说明这一点，例如：https://github.com/cipchk/vscode-cssrem/blob/master/.cssrem
