### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by DreAdeDcoRpSE** [cipchk/vscode-cssrem#45]
I tried installing this extension and once installed and enabled. When I go in a CSS file and try to use it, using the shortcut keys, I get:

_**command 'extension.cssrem.rem-switch-px' not found**_

I tried the other command and it is also not found.:

_**command 'extension.cssrem.rem-switch-px' not found**_

Any idea?

**Comment by cipchk** [comment]
Can you open the developer tools to see if there are any exceptions, or try reinstall latest versionn.

**Comment by DreAdeDcoRpSE** [comment]
I've uninstalled & reinstalled. Event put  v2.5.1 on to see if that would work and same thing. In the log I was able to get this.

> mainThreadExtensionService.ts:95 Activating extension 'cipchk.cssrem' failed: Cannot read property 'length' of undefined.
> $onExtensionActivationError @ mainThreadExtensionService.ts:95
> _doInvokeHandler @ rpcProtocol.ts:472
> _invokeHandler @ rpcProtocol.ts:457
> _receiveRequest @ rpcProtocol.ts:373
> _receiveOneMessage @ rpcProtocol.ts:295
> (anonymous) @ rpcProtocol.ts:160
> fire @ event.ts:577
> fire @ ipc.net.ts:513
> _receiveMessage @ ipc.net.ts:871
> (anonymous) @ ipc.net.ts:710
> fire @ event.ts:577
> acceptChunk @ ipc.net.ts:286
> (anonymous) @ ipc.net.ts:247
> k @ ipc.net.ts:50
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> console.ts:137 [Extension Host] Git installation not found.
> E @ console.ts:137
> $logExtensionHostMessage @ mainThreadConsole.ts:39
> _doInvokeHandler @ rpcProtocol.ts:472
> _invokeHandler @ rpcProtocol.ts:457
> _receiveRequest @ rpcProtocol.ts:373
> _receiveOneMessage @ rpcProtocol.ts:295
> (anonymous) @ rpcProtocol.ts:160
> fire @ event.ts:577
> fire @ ipc.net.ts:513
> _receiveMessage @ ipc.net.ts:871
> (anonymous) @ ipc.net.ts:710
> fire @ event.ts:577
> acceptChunk @ ipc.net.ts:286
> (anonymous) @ ipc.net.ts:247
> k @ ipc.net.ts:50
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188

**Comment by DreAdeDcoRpSE** [comment]
Okay, Update to the previous post. I updated back to the latest version, opened up my project, and didn't work, I kept getting the same message even after a couple of reloads. I then went and opened up my other project, and it started working, sort of. 

Alt+Z does switch between px and rem, but, then I tried pressing Alt+R and I get the error:

> command 'extension.cssrem.rpx-switch-px' not found

**Comment by cipchk** [comment]
About `rpx-switch-px`, you need to enable `wxss` support first.

**Comment by makk24** [comment]
command 'extension.cssrem.rpx-switch-px' not found  
Any idea?

**Comment by makk24** [comment]
> About `rpx-switch-px`, you need to enable `wxss` support first.

command 'extension.cssrem.rpx-switch-px' not found
Any idea?

**Comment by mohit-codes** [comment]
_command 'extension.cssrem.rem-switch-px' not found_

I am having the same issue, I tried enabling `wxss` support but the issue is still not resolved. The extension was working fine a few days ago. I've also tried installing previous versions but nothing worked.

**Comment by cipchk** [comment]
@mohit-codes Working for my mac component, gif:

![Kapture 2022-03-28 at 16 17 26](https://user-images.githubusercontent.com/2987467/160356196-6edb4cb3-e118-4e55-887d-9d481cde2d7d.gif)

**Comment by mohit-codes** [comment]
> @mohit-codes Working for my mac component, gif:
> 
> ![Kapture 2022-03-28 at 16 17 26](https://user-images.githubusercontent.com/2987467/160356196-6edb4cb3-e118-4e55-887d-9d481cde2d7d.gif)

After enabling `wxss` for that specific workspace now the issue is resolved, extension is working fine.

**Comment by vhunko** [comment]
got same issue today: `command 'extension.cssrem.rem-switch-px' not found`
any ideas why it could happen?

**Comment by godkun** [comment]
@vhunko 最新解决方案：vscode 卸载这个插件，然后再安装，应该就可以了。具体原因不详

**Comment by Michael-Obele** [comment]
Got this today  `Command 'CSSRem: Px To VW' resulted in an error (command 'extension.cssrem.px-to-vw' not found)`

I haven't used the VW converter before. However, the extension displays a mark after the line containing the converted value, but it is unable to input it when the command is invoked.

It works when I type in CSS files and use autocomplete to convert them, but when I highlight and call the command, I get the error. As a result, it cannot be used in JSX files where autocomplete does not appear.

**Comment by YOYOsheep** [comment]
![微信截图_20220819101014](https://user-images.githubusercontent.com/8286721/185527591-f4596167-f553-4a5b-ac74-74908865fa8a.jpg)
我也有相同的问题

**Comment by cipchk** [comment]
@YOYOsheep I fixed a bug that hides `length`, please try to update to `3.0.1`.

>> cc @Michael-Obele @godkun @vhunko @mohit-codes @makk24

**Comment by YOYOsheep** [comment]
![Uploading 微信截图_20220819101014.jpg…]()
已经重新安装3.0.1版本，运行状态依然是“尚未激活”，VScode已经升级到最新。

**Comment by YOYOsheep** [comment]
![微信截图_20220819101014](https://user-images.githubusercontent.com/8286721/185560948-f5cf9bb0-13f7-47a6-8dcd-d93355ea87be.jpg)
已经重新安装3.0.1版本，运行状态依然是“尚未激活”，VScode已经升级到最新。

**Comment by cipchk** [comment]
fixed `3.0.2`.

**Comment by YOYOsheep** [comment]
@cipchk Solved, thanks

**Comment by wangshikun2010** [comment]
Just restart the VScode
