### ISSUE TITLE
[renderer1] Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by justerror** [cipchk/vscode-cssrem#48]
### Environment

Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

### Reproduce: 
1. Open Output -> Select "Log (Window)"
2. Open file/Navigate through files in editor
3. Error will be occurred

`[2022-02-22 18:47:25.211] [renderer1] [error] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at LineAnnotation.onActiveTextEditor (/Users/justerror/.vscode/extensions/cipchk.cssrem-2.7.0/out/line-annotation.js:29:16)`

<img width="850" alt="image" src="https://user-images.githubusercontent.com/17014639/155168543-6fb47d25-ce64-4fe5-9f1c-ef7ad45b4577.png">

### Possible cause:

onDidChangeActiveTextEditor: [Event](https://code.visualstudio.com/api/references/vscode-api#Event)<[TextEditor](https://code.visualstudio.com/api/references/vscode-api#TextEditor) | [undefined]()>

An [Event](https://code.visualstudio.com/api/references/vscode-api#Event) which fires when the [active editor](https://code.visualstudio.com/api/references/vscode-api#window.activeTextEditor) has changed. Note that the event also fires when the active editor changes to **undefined**.

**Comment by cipchk** [comment]
fixed by `2.7.1`.
