### ISSUE TITLE
请问在vue哪里配置我是用vue脚手架构架的项目

### ISSUE THREAD

**Issue by cynthiamatthew** [cipchk/vscode-cssrem#5]
cssrem.rootFontSize root font-size (unit: px), default: 16
cssrem.fixedDigits px转rem小数点最大长度，默认：6。
cssrem.autoRemovePrefixZero 自动移除0开头的前缀，默认：true

**Comment by cipchk** [comment]
file -> preferences -> Settings.

**Comment by cynthiamatthew** [comment]
谢谢，已经解决了。
 
 
------------------ Original ------------------
