### ISSUE TITLE
Does anyone knows why my preview is not working?

### ISSUE THREAD

**Issue by sushanyadav** [cipchk/vscode-cssrem#53]
Issue:
![CleanShot 2022-11-02 at 12 10 25](https://user-images.githubusercontent.com/53527664/199309738-daa4d73a-58ed-42d7-a0e6-482374e1ffb1.png)

Expected:
![CleanShot 2022-11-02 at 12 12 18](https://user-images.githubusercontent.com/53527664/199310017-375c9d69-5d58-48dc-bbdf-3a4188f41f6b.png)

**Comment by cipchk** [comment]
@sushanyadav  PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)

**Comment by sushanyadav** [comment]
> @sushanyadav PASTE OUTPUT OF DEVELOPER TOOLS CONSOLE (Help -> Toggle Developer Tools -> Select Console tab)


https://user-images.githubusercontent.com/53527664/200120853-bc1ddbef-b9a4-4b8b-a0eb-cb0918f6a069.mp4

**Comment by cipchk** [comment]
Maybe a configuration problem? you can be set `Hover` property? (Mybe reset vscode.)

<img width="450" alt="image" src="https://user-images.githubusercontent.com/2987467/200122034-a4ff0165-81a2-4667-bdaa-31d4e8e18b40.png">

**Comment by sushanyadav** [comment]
It is set to always..
![CleanShot 2022-11-05 at 8 03 17](https://user-images.githubusercontent.com/53527664/200124280-3b171116-f5fe-476a-9afa-61bf3dc5c6b3.png)

**Comment by cipchk** [comment]
@sushanyadav No any errors, no configuration errors. Do you want to try reinstalling vscode-cssrem?

**Comment by sushanyadav** [comment]
Yea tried. like many times.

**Comment by cipchk** [comment]
Any other working except for hover? such as intellisense?

**Comment by sushanyadav** [comment]
Alt + Z converts px to rem. but yea only hover is not not working..

**Comment by sushanyadav** [comment]
Apologies. had to remove this piece.
![CleanShot 2022-11-08 at 4 36 17](https://user-images.githubusercontent.com/53527664/200545879-968f5d7c-e896-4893-afc3-489de01e4322.png)
