### ISSUE TITLE
[feature request] Allow for px-rem conversion to work in *.cjs files

### ISSUE THREAD

**Issue by p0psicles** [cipchk/vscode-cssrem#54]
# 🐛 What is the bug? How can we reproduce it?

Create a .cjs file.
For example i'm using `tailwind.config.cjs` for tailwind configuration.
The px->rem or rem->px hints are not showing.

## Expected behavior

What were you expecting to happen?
To show hints

## What I tried myself
I added `cjs` (extension) to the ccsrem.languages config option.
![image](https://user-images.githubusercontent.com/1331394/222388415-2d432e6d-3050-4100-bed1-e580b811c9b8.png)

## Environment
Ubuntu 22.10.

```text
Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:35:30.018Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 5.19.0-31-generic snap
Sandboxed: No
```

**Comment by cipchk** [comment]
cjs should not be used here, it is not a language. I have added support for `javascript`, `typescript` language in version `3.1.0`.

**Comment by p0psicles** [comment]
How do I get it to recognize cjs as javascript?
