### ISSUE TITLE
[Bug]  px -> vw function failed

### ISSUE THREAD

**Issue by Dev-Hogan** [cipchk/vscode-cssrem#56]
Use px -> vw (Shortcut key: Alt + v, Alt + w) function failed. Even if you change the setting to true."cssrem.vw": true still no use.
Hope it will improve soon

**Comment by cipchk** [comment]
Sorry, busy work, can you provider your env?

**Comment by 15200596294git** [comment]
I had the same problem

**Comment by 15200596294git** [comment]
My version of visual studio code is 1.81.1 (Universal), and operation system is Apple.My problem is that the unit will still be px after using the shortcut key(Option + V, Option + W), and the value will become larger.

**Comment by jokerdragon7** [comment]
For example, when developing a mobile project using iPhone 6/7/8 as a template, 1vw=3.75px. When I want to convert 10px to vw units, it should be 10/3.75=2.6666 vw. However, when using the shortcut keys alt+v, alt+w, it will become 10 * 3.75=37.5. Other functions are fine, but there is a bug at this point

**Comment by cipchk** [comment]
Fixed by `3.1.1`.
