### ISSUE TITLE
Add support for px / rem to em? (Suggestion)

### ISSUE THREAD

**Issue by Project49Music** [cipchk/vscode-cssrem#57]
Hello there,

I am currently a front-end developer using your extension and love it. Recently we as a team started using line-heights in em instead of rem and we were wondering if you agree with the idea of integrating a calculation that also shows an em option.

I'd like to hear your thoughts.

Kind regards,
Dylan

**Comment by cipchk** [comment]
Hi, you can add conversion rules through the `rules.ts` file, likt px to rem rule: 

```ts
https://github.com/cipchk/vscode-cssrem/blob/master/src/rules.ts#L21-L64
```

**Comment by Project49Music** [comment]
Thank you for the information, I'll mark the issues as completed now! 😄
