### ISSUE TITLE
cssrem tailwind 不起作用

### ISSUE THREAD

**Issue by LBC000** [cipchk/vscode-cssrem#60]
h-[100px] 没有提示

**Comment by bronisMateusz** [comment]
It seems to be working:
<img width="338" alt="Zrzut ekranu 2024-09-27 o 09 04 04" src="https://github.com/user-attachments/assets/74519b5e-db08-4f9f-a5fb-28e40abb3f58">
<img width="323" alt="Zrzut ekranu 2024-09-27 o 09 04 15" src="https://github.com/user-attachments/assets/64b68789-389a-4d5f-9de3-f8c07c434ff0">

**Comment by Paxtony** [comment]
> It seems to be working: <img alt="Zrzut ekranu 2024-09-27 o 09 04 04" width="338" src="https://private-user-images.githubusercontent.com/45051768/371429318-74519b5e-db08-4f9f-a5fb-28e40abb3f58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTE4ODEsIm5iZiI6MTcyODg5MTU4MSwicGF0aCI6Ii80NTA1MTc2OC8zNzE0MjkzMTgtNzQ1MTliNWUtZGIwOC00ZjlmLWE1ZmItMjhlNDBhYmIzZjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA3Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTNlNDM1ZGY1OWQwN2JjN2MxNmM1YzJlZDdlMWU3N2RjYzJlN2JiMDgwYmE4OGQ4OGEyODIwMmIwNTBlNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V2G06XofCGQDJ6iFwo-sJHSoDBiw8PdW-5D7DHLIiwk"> <img alt="Zrzut ekranu 2024-09-27 o 09 04 15" width="323" src="https://private-user-images.githubusercontent.com/45051768/371429372-64b68789-389a-4d5f-9de3-f8c07c434ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTE4ODEsIm5iZiI6MTcyODg5MTU4MSwicGF0aCI6Ii80NTA1MTc2OC8zNzE0MjkzNzItNjRiNjg3ODktMzg5YS00ZDVmLTlkZTMtZjhjMDdjNDM0ZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA3Mzk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYmMwMWViN2ZkNTI3MTJiNjMwNDQ0Zjc5ZDI0OWJmMmRiYTVmYzllMDNmOTczMGRkYzkwNzFjYWM5N2RkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XOsrXfwvSds0ONqwKEplkSFvJzKivJBYYRHN8MBDtYg">

i did it your way, but not work

**Comment by cipchk** [comment]
I can also working, gif:

![Untitled](https://github.com/user-attachments/assets/22037ae0-1b3b-4077-9011-bb6f2c703d7b)

**Comment by Denricoro** [comment]
> I can also working, gif:
> 
> ![Untitled](https://private-user-images.githubusercontent.com/2987467/376740348-22037ae0-1b3b-4077-9011-bb6f2c703d7b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDMyNjMsIm5iZiI6MTcyOTA0Mjk2MywicGF0aCI6Ii8yOTg3NDY3LzM3Njc0MDM0OC0yMjAzN2FlMC0xYjNiLTQwNzctOTAxMS1iYjZmMmM3MDNkN2IuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDE0MjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDUzNTUwZTBiNzU3ZDE0NWJjODRmZjVhYWM4Y2IwMDQwMmNhMzFkOTQ0ZmFhYzEzMGZkYjM0OTljZmQ3YjQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5trfA0IIP_Rs4g086WxV6SzJ4_CCc2oTvZ0h7fLXqYQ) [ ![Untitled](https://private-user-images.githubusercontent.com/2987467/376740348-22037ae0-1b3b-4077-9011-bb6f2c703d7b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDMyNjMsIm5iZiI6MTcyOTA0Mjk2MywicGF0aCI6Ii8yOTg3NDY3LzM3Njc0MDM0OC0yMjAzN2FlMC0xYjNiLTQwNzctOTAxMS1iYjZmMmM3MDNkN2IuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDE0MjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDUzNTUwZTBiNzU3ZDE0NWJjODRmZjVhYWM4Y2IwMDQwMmNhMzFkOTQ0ZmFhYzEzMGZkYjM0OTljZmQ3YjQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5trfA0IIP_Rs4g086WxV6SzJ4_CCc2oTvZ0h7fLXqYQ) ](https://private-user-images.githubusercontent.com/2987467/376740348-22037ae0-1b3b-4077-9011-bb6f2c703d7b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDMyNjMsIm5iZiI6MTcyOTA0Mjk2MywicGF0aCI6Ii8yOTg3NDY3LzM3Njc0MDM0OC0yMjAzN2FlMC0xYjNiLTQwNzctOTAxMS1iYjZmMmM3MDNkN2IuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDE0MjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDUzNTUwZTBiNzU3ZDE0NWJjODRmZjVhYWM4Y2IwMDQwMmNhMzFkOTQ0ZmFhYzEzMGZkYjM0OTljZmQ3YjQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5trfA0IIP_Rs4g086WxV6SzJ4_CCc2oTvZ0h7fLXqYQ) [ ](https://private-user-images.githubusercontent.com/2987467/376740348-22037ae0-1b3b-4077-9011-bb6f2c703d7b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDMyNjMsIm5iZiI6MTcyOTA0Mjk2MywicGF0aCI6Ii8yOTg3NDY3LzM3Njc0MDM0OC0yMjAzN2FlMC0xYjNiLTQwNzctOTAxMS1iYjZmMmM3MDNkN2IuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDE0MjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDUzNTUwZTBiNzU3ZDE0NWJjODRmZjVhYWM4Y2IwMDQwMmNhMzFkOTQ0ZmFhYzEzMGZkYjM0OTljZmQ3YjQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5trfA0IIP_Rs4g086WxV6SzJ4_CCc2oTvZ0h7fLXqYQ)

I guess it's because of the list of supported languages,I used jsx and tailwinds for the style.
Current list is provided by default language [' HTML ', 'vue', 'CSS', 'postcss', 'less', 'SCSS', 'sass', 'stylus',' the TPL ', 'WXSS', 'twig is, 'javascriptreact', 'typescriptreact', 'javascript', 'typescript' ]
how do I add jsx and tailwindcss to it?

**Comment by cipchk** [comment]
I think it might be due to javascriptreat (or jsx). By default, vscode doesn’t auto-trigger completions within strings. Maybe you can add the following configuration to current project (`.vscode/settings.json`) to fix it:

```json
{
  "editor.quickSuggestions": {
		"other": true,
		"comments": false,
		"strings": true
	}
}
```
