### ISSUE TITLE
希望能在批量转换的时候，对媒体查询的位置 能设置过滤

### ISSUE THREAD

**Issue by wangaicc** [cipchk/vscode-cssrem#61]
![image](https://github.com/user-attachments/assets/79c1990c-8838-457c-b4b3-1fd2b9a92a76)

希望能加个在批量PX转换REM的时候 对媒体查询的位置的这个转化rem的过滤。。
个人觉得方便查看

I hope to add a filter for converting REM when batch converting PX, specifically for the position of media queries. Personally, I think this would make it easier and more intuitive to view media queries.

**Comment by cipchk** [comment]
能否进一步说明呢？

**Comment by cipchk** [comment]
fixed by `4.0.0`.
