### ISSUE TITLE
与Ctrl + P的快捷键冲突

### ISSUE THREAD

**Issue by iamzhaobo** [cipchk/vscode-cssrem#9]
VScode中Ctrl + P的作用是快速查找文件，安装cssrem插件后，按下Ctrl + P不能达到预期查找文件的效果，而是提示按下一个组合快捷键

**Comment by cipchk** [comment]
使用了一个组合快捷键：`ctrl+p ctrl+r`，我的环境里并没有污染到查找文件，可以查看所有快捷键是否有其他影响。

**Comment by iamzhaobo** [comment]
只要卸载了cssrem插件并reload之后，`ctrl + p`就恢复正常了，不然它就会出现如下提示
![image](https://user-images.githubusercontent.com/17156560/42748549-2b73ff08-8913-11e8-8260-acc9a5d4e618.png)

**Comment by cipchk** [comment]
谢谢反馈，暂时你先重置掉 `ctrl+p ctrl+r`，方法是点
![tim 20180716161905](https://user-images.githubusercontent.com/2987467/42748776-fa4b4692-8913-11e8-8dca-9f57fe0ced1a.png)
搜索：`cssrem` 重新指定一下其他快捷键。
